config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'items#index'
  resources :shopping_experiences 

  
  get 'items/search', to: 'items#search', as: :search 
  resources :items
  resources :categories
   
  


    resources :shex_items 
    post  'shopping_experience/add_to_cart', to: 'shopping_experiences#add_to_cart' , as: :add_to_cart 
    
   
    

      get 'shopping_experience/my_cart', to: 'shopping_experiences#display_cart', as: :display_cart


      post '/shopping_experience/delete_from_my_cart_/:item_id', to: 'shopping_experiences#delete_from_my_cart', as: :delete_item_from_cart

      post '/shopping_experience/check_out', to: 'shopping_experiences#check_out', as: :checkout
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shopping_experience.rb
class ShoppingExperience < ApplicationRecord
end

app/controllers/shopping_experiences_controller.rb
class ShoppingExperiencesController < ApplicationController
  before_action :set_shopping_experience, only: [:show, :edit, :update, :destroy]

  def display_cart
    
    if session[:current_cart]
    @cart = session[:current_cart].except("shex_id")
    end 
    
  
   
    render 'displayCart'
    
  end

  def check_out
    Stripe.api_key = 'sk_test_nvFyasCVrO6uUNIOtyCZyM0L00eqn9vlgM'

    # Token is created using Stripe Checkout or Elements!
   # Get the payment token ID submitted by the form:
  
    token = params[:stripeToken]
 
     charge = Stripe::Charge.create({
       amount: 999,
       currency: 'aud',
       description: 'Example charge',
        source: token,
     })
      
  end

  def delete_from_my_cart
    

    session[:current_cart].delete(params[:item_id])
    #  session[:current_cart][parmas[:item_id]].delete
    redirect_to display_cart_url
  end

  def add_to_cart
  
   
    if !session[:current_cart] 
      session[:current_cart] =  {:shex_id => session[:current_cart_id] } 
    end
    
    
   

       #checks if session hash's current cart key doesn't have params[:item_id] key, value pair 
       if  !session[:current_cart].key?(params[:item_id]) 
        # set {units: 1}  as params[item_id] key's  value 
        
        session[:current_cart][params[:item_id]] = {}
        session[:current_cart][params[:item_id]][:quantity] = 1
       
       
         
        
   else
     
       #else  increment  value  of  quantity
        
       session[:current_cart][params[:item_id]]["quantity"] = session[:current_cart][params[:item_id]]["quantity"] + 1
       #ShexItem.create(item_id: params[:item_id], shopping_experience_id: session[:current_cart_id] ) 
       
    end
   
   puts(' at to cart method end  ... . . . . . . . . .
   sewdwdwdw  ')

   redirect_to  '/'
end
  # GET /shopping_experiences
  # GET /shopping_experiences.json
  def index
    @shopping_experiences = ShoppingExperience.all
  end

  # GET /shopping_experiences/1
  # GET /shopping_experiences/1.json
  def show
  end

  # GET /shopping_experiences/new
  def new
    @shopping_experience = ShoppingExperience.new
  end

  # GET /shopping_experiences/1/edit
  def edit
  end

  # POST /shopping_experiences
  # POST /shopping_experiences.json
  def create
    @shopping_experience = ShoppingExperience.new(shopping_experience_params)

    respond_to do |format|
      if @shopping_experience.save
        format.html { redirect_to @shopping_experience, notice: 'Shopping experience was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_experience }
      else
        format.html { render :new }
        format.json { render json: @shopping_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_experiences/1
  # PATCH/PUT /shopping_experiences/1.json
  def update
    respond_to do |format|
      if @shopping_experience.update(shopping_experience_params)
        format.html { redirect_to @shopping_experience, notice: 'Shopping experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_experience }
      else
        format.html { render :edit }
        format.json { render json: @shopping_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_experiences/1
  # DELETE /shopping_experiences/1.json
  def destroy
    @shopping_experience.destroy
    respond_to do |format|
      format.html { redirect_to shopping_experiences_url, notice: 'Shopping experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_experience
      @shopping_experience = ShoppingExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_experience_params
      params.fetch(:shopping_experience, {})
    end
end

app/helpers/shopping_experiences_helper.rb
module ShoppingExperiencesHelper
end

app/views/shopping_experiences/_form.html.erb
<%= form_with(model: shopping_experience, local: true) do |form| %>
  <% if shopping_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_experience.errors.count, "error") %> prohibited this shopping_experience from being saved:</h2>

      <ul>
        <% shopping_experience.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_experiences/displayCart.html.erb
<%=link_to 'back', items_path %>
<p> Your  cart</p>

<%if session[:current_cart] %>

<% @cart.each do |key,value| %>
      
    <% item = Item.find(key.to_i)%>
    
    <% #value {"quantity": "number"} %> 

        <%= item.name %> 
         <%= item.price %> 
  
          
           <%= item.quantity %> 
           <%= item.category.title %>
           quantity : <%= value["quantity"]%>  
          <button class="cart_plus_button"> + </button> 
          <button class="cart_minus_button"> - </button> 
          

         
         <%= link_to 'delete', delete_item_from_cart_path(item.id),method: :post  %>
        

      </br>
      
    
  <% end %>


  <% end %>
 
  <form action="/shopping_experience/check_out" method="post" id="payment-form">
  <%=hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %> 
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>
  <%= link_to 'checkout', checkout_path ,method: :post  %>

app/views/shopping_experiences/edit.html.erb
<h1>Editing Shopping Experience</h1>

<%= render 'form', shopping_experience: @shopping_experience %>

<%= link_to 'Show', @shopping_experience %> |
<%= link_to 'Back', shopping_experiences_path %>

app/views/shopping_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Experiences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_experiences.each do |shopping_experience| %>
      <tr>
        <td><%= link_to 'Show', shopping_experience %></td>
        <td><%= link_to 'Edit', edit_shopping_experience_path(shopping_experience) %></td>
        <td><%= link_to 'Destroy', shopping_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping Experience', new_shopping_experience_path %>

app/views/shopping_experiences/new.html.erb
<h1>New Shopping Experience</h1>

<%= render 'form', shopping_experience: @shopping_experience %>

<%= link_to 'Back', shopping_experiences_path %>

app/views/shopping_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shopping_experience_path(@shopping_experience) %> |
<%= link_to 'Back', shopping_experiences_path %>