config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'items#index'
  resources :shopping_experiences 

  
  get 'items/search', to: 'items#search', as: :search 
  resources :items
  resources :categories
   
  


    resources :shex_items 
    post  'shopping_experience/add_to_cart', to: 'shopping_experiences#add_to_cart' , as: :add_to_cart 
    
   
    

      get 'shopping_experience/my_cart', to: 'shopping_experiences#display_cart', as: :display_cart


      post '/shopping_experience/delete_from_my_cart_/:item_id', to: 'shopping_experiences#delete_from_my_cart', as: :delete_item_from_cart

      post '/shopping_experience/check_out', to: 'shopping_experiences#check_out', as: :checkout
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  has_many_attached :images
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    
    # reset_session
    if !session[:current_cart_id]
      new_shex = ShoppingExperience.create
      session[:current_cart_id] = new_shex.id
    end
    
    @items = Item.all
  
  end


  def search

     
     if params[:category]
     @items = Item.where(category_id: Category.find_by(title: params[:category]).id )
     else
      @items = Item.all
     end

    
 

  end


  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :quantity, :category_id,images: [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>



  <div class="field">
    <%= form.label :category_id %>
    <%= collection_radio_buttons(:item, :category_id, Category.all, :id, :title)%>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'layouts/partials/Banner' %>

</br>







<section class="">
		<!-- single product slide -->
		<div class="">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Latest Products</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
								dolore
								magna aliqua.</p>
						</div>
					</div>
				</div>
        <div class="row">
        
          <% @items.each do |item|   %>
            
           <%= render 'layouts/partials/IndexItem', :locals=>{item: item}  %>

           <%end%>
          



				
          


				
				</div>
			</div>
    </div>
    

		
		
	</section>
	<!-- end product Area -->
	

	




	

	

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
  <%= render 'layouts/partials/PicturelessBanner' %>	
	
	<div class="container">
		<div class="row">

		       <%= render 'items/partials/SidebarCategories', :locals=> {categories: Category.all }%>
               <%= render 'items/partials/SidebarBrands'%>

				
			</div>
			<div class="col-xl-9 col-lg-8 col-md-7">
				 <%=render 'items/partials/FilterOptions' %>


				<!-- Start Best Seller -->
				<section class="lattest-product-area pb-40 category-list">
					<div class="row">

					     <% @items.each do |item| %>
						 <%= render 'layouts/partials/IndexItem', :locals=>{item: item} %>
						 <%end%>


						<div>
				</section>
				<!-- End Best Seller -->
				<!-- Start Filter Bar -->
				<%= render 'items/partials/FilterOptions' %>
				<!-- End Filter Bar -->
			</div>
		</div>
	</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>


<p>
  <strong>Pictures:</strong>
  
<%= image_tag url_for(@item.images[1]) %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>