config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'items#index'
  resources :shopping_experiences 

  
  get 'items/search', to: 'items#search', as: :search 
  resources :items
  resources :categories
   
  


    resources :shex_items 
    post  'shopping_experience/add_to_cart', to: 'shopping_experiences#add_to_cart' , as: :add_to_cart 
    
   
    

      get 'shopping_experience/my_cart', to: 'shopping_experiences#display_cart', as: :display_cart


      post '/shopping_experience/delete_from_my_cart_/:item_id', to: 'shopping_experiences#delete_from_my_cart', as: :delete_item_from_cart

      post '/shopping_experience/check_out', to: 'shopping_experiences#check_out', as: :checkout
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shex_item.rb
class ShexItem < ApplicationRecord
  belongs_to :item
  belongs_to :shopping_experience
end

app/controllers/shex_items_controller.rb
class ShexItemsController < ApplicationController
  before_action :set_shex_item, only: [:show, :edit, :update, :destroy]

  # GET /shex_items
  # GET /shex_items.json
  def index
    @shex_items = ShexItem.all
  end






  # GET /shex_items/1
  # GET /shex_items/1.json
  def show
  end

  # GET /shex_items/new
  def new
    @shex_item = ShexItem.new
  end

  # GET /shex_items/1/edit
  def edit
  end

  # POST /shex_items
  # POST /shex_items.json
  def create
    @shex_item = ShexItem.new(shex_item_params)

    respond_to do |format|
      if @shex_item.save
        format.html { redirect_to @shex_item, notice: 'Shex item was successfully created.' }
        format.json { render :show, status: :created, location: @shex_item }
      else
        format.html { render :new }
        format.json { render json: @shex_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shex_items/1
  # PATCH/PUT /shex_items/1.json
  def update
    respond_to do |format|
      if @shex_item.update(shex_item_params)
        format.html { redirect_to @shex_item, notice: 'Shex item was successfully updated.' }
        format.json { render :show, status: :ok, location: @shex_item }
      else
        format.html { render :edit }
        format.json { render json: @shex_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shex_items/1
  # DELETE /shex_items/1.json
  def destroy
    @shex_item.destroy
    respond_to do |format|
      format.html { redirect_to shex_items_url, notice: 'Shex item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shex_item
      @shex_item = ShexItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shex_item_params
      params.require(:shex_item).permit(:item_id, :shopping_experience_id)
    end
end

app/helpers/shex_items_helper.rb
module ShexItemsHelper
end

app/views/shex_items/_form.html.erb
<%= form_with(model: shex_item, local: true) do |form| %>
  <% if shex_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shex_item.errors.count, "error") %> prohibited this shex_item from being saved:</h2>

      <ul>
        <% shex_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :shopping_experience_id %>
    <%= form.text_field :shopping_experience_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shex_items/edit.html.erb
<h1>Editing Shex Item</h1>

<%= render 'form', shex_item: @shex_item %>

<%= link_to 'Show', @shex_item %> |
<%= link_to 'Back', shex_items_path %>

app/views/shex_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shex Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Shopping experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shex_items.each do |shex_item| %>
      <tr>
        <td><%= shex_item.item_id %></td>
        <td><%= shex_item.shopping_experience_id %></td>
        <td><%= link_to 'Show', shex_item %></td>
        <td><%= link_to 'Edit', edit_shex_item_path(shex_item) %></td>
        <td><%= link_to 'Destroy', shex_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shex Item', new_shex_item_path %>

app/views/shex_items/new.html.erb
<h1>New Shex Item</h1>

<%= render 'form', shex_item: @shex_item %>

<%= link_to 'Back', shex_items_path %>

app/views/shex_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @shex_item.item_id %>
</p>

<p>
  <strong>Shopping experience:</strong>
  <%= @shex_item.shopping_experience_id %>
</p>

<%= link_to 'Edit', edit_shex_item_path(@shex_item) %> |
<%= link_to 'Back', shex_items_path %>